language: cpp
os: linux
dist: xenial
addons:
  apt:
    packages:
      - build-essential

script:
  - make

after_success:
  - tar cvzf triplet_challenge_stats.tar.gz triplet_challenge_stats triplet_challenge_preload.so
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh triplet_challenge_stats.tar.gz
